// citiesData.ts
import { z } from "zod";

export const citySchema = z.object({
  id: z.string(),
  name: z.string(),
  events: z.number(),
  icon: z.string(),
  followed: z.boolean(),
  color: z.string(),
  region: z.string(),
});

export type City = z.infer<typeof citySchema>;

export const cities: City[] = [
  {
    id: "0196b41c-21d0-769c-8542-ab83908ef93c",
    name: "Bangkok",
    events: 28,
    icon: "🏯",
    followed: false,
    color: "bg-orange-500",
    region: "Châu Á & Thái Bình Dương",
  },
  {
    id: "2",
    name: "Bengaluru",
    events: 30,
    icon: "🏰",
    followed: false,
    color: "bg-yellow-600",
    region: "Châu Á & Thái Bình Dương",
  },
  {
    id: "3",
    name: "Dubai",
    events: 7,
    icon: "🕌",
    followed: false,
    color: "bg-purple-600",
    region: "Châu Á & Thái Bình Dương",
  },
  {
    id: "4",
    name: "Đài Bắc",
    events: 20,
    icon: "🗼",
    followed: false,
    color: "bg-blue-600",
    region: "Châu Á & Thái Bình Dương",
  },
  {
    id: "5",
    name: "Honolulu",
    events: 7,
    icon: "🌊",
    followed: false,
    color: "bg-blue-400",
    region: "Châu Á & Thái Bình Dương",
  },
  {
    id: "6",
    name: "Hồng Kông",
    events: 29,
    icon: "🌆",
    followed: false,
    color: "bg-green-500",
    region: "Châu Á & Thái Bình Dương",
  },
  {
    id: "7",
    name: "Jakarta",
    events: 3,
    icon: "🏙️",
    followed: false,
    color: "bg-yellow-700",
    region: "Châu Á & Thái Bình Dương",
  },
  {
    id: "8",
    name: "Kuala Lumpur",
    events: 13,
    icon: "🕌",
    followed: false,
    color: "bg-purple-700",
    region: "Châu Á & Thái Bình Dương",
  },
  {
    id: "9",
    name: "Manila",
    events: 10,
    icon: "🏝️",
    followed: false,
    color: "bg-teal-500",
    region: "Châu Á & Thái Bình Dương",
  },
  {
    id: "10",
    name: "Melbourne",
    events: 17,
    icon: "🏟️",
    followed: false,
    color: "bg-green-600",
    region: "Châu Á & Thái Bình Dương",
  },
  {
    id: "11",
    name: "Mumbai",
    events: 9,
    icon: "🏗️",
    followed: false,
    color: "bg-orange-600",
    region: "Châu Á & Thái Bình Dương",
  },
  {
    id: "12",
    name: "New Delhi",
    events: 11,
    icon: "🏛️",
    followed: false,
    color: "bg-red-400",
    region: "Châu Á & Thái Bình Dương",
  },
  {
    id: "13",
    name: "Seoul",
    events: 15,
    icon: "🏯",
    followed: false,
    color: "bg-blue-500",
    region: "Châu Á & Thái Bình Dương",
  },
  {
    id: "14",
    name: "Singapore",
    events: 0,
    icon: "🌉",
    followed: true,
    color: "bg-green-700",
    region: "Châu Á & Thái Bình Dương",
  },
  {
    id: "15",
    name: "Sydney",
    events: 17,
    icon: "🌁",
    followed: false,
    color: "bg-orange-500",
    region: "Châu Á & Thái Bình Dương",
  },
  {
    id: "16",
    name: "Tel Aviv-Yafo",
    events: 29,
    icon: "🏙️",
    followed: false,
    color: "bg-orange-400",
    region: "Châu Á & Thái Bình Dương",
  },
  {
    id: "17",
    name: "Tokyo",
    events: 30,
    icon: "🗼",
    followed: false,
    color: "bg-red-500",
    region: "Châu Á & Thái Bình Dương",
  },
  {
    id: "18",
    name: "TP. Hồ Chí Minh",
    events: 0,
    icon: "🏙️",
    followed: true,
    color: "bg-red-500",
    region: "Châu Á & Thái Bình Dương",
  },
  {
    id: "19",
    name: "Amsterdam",
    events: 30,
    icon: "🏰",
    followed: false,
    color: "bg-red-500",
    region: "Châu Âu",
  },
  {
    id: "20",
    name: "Barcelona",
    events: 17,
    icon: "🏛️",
    followed: false,
    color: "bg-blue-500",
    region: "Châu Âu",
  },
  {
    id: "21",
    name: "Berlin",
    events: 43,
    icon: "🗼",
    followed: false,
    color: "bg-blue-600",
    region: "Châu Âu",
  },
  {
    id: "22",
    name: "Brussels",
    events: 14,
    icon: "🏰",
    followed: false,
    color: "bg-blue-600",
    region: "Châu Âu",
  },
  {
    id: "23",
    name: "Copenhagen",
    events: 8,
    icon: "🏰",
    followed: false,
    color: "bg-orange-500",
    region: "Châu Âu",
  },
  {
    id: "24",
    name: "Helsinki",
    events: 10,
    icon: "🏯",
    followed: false,
    color: "bg-teal-500",
    region: "Châu Âu",
  },
  {
    id: "25",
    name: "Istanbul",
    events: 9,
    icon: "🕌",
    followed: false,
    color: "bg-orange-600",
    region: "Châu Âu",
  },
  {
    id: "26",
    name: "Lisbon",
    events: 15,
    icon: "🏝️",
    followed: false,
    color: "bg-orange-400",
    region: "Châu Âu",
  },
  {
    id: "27",
    name: "London",
    events: 66,
    icon: "🏙️",
    followed: false,
    color: "bg-yellow-600",
    region: "Châu Âu",
  },
  {
    id: "28",
    name: "Madrid",
    events: 14,
    icon: "🏰",
    followed: false,
    color: "bg-green-600",
    region: "Châu Âu",
  },
  {
    id: "29",
    name: "Milan",
    events: 11,
    icon: "🏛️",
    followed: false,
    color: "bg-brown-600",
    region: "Châu Âu",
  },
  {
    id: "30",
    name: "Munich",
    events: 10,
    icon: "🏗️",
    followed: false,
    color: "bg-yellow-500",
    region: "Châu Âu",
  },
  {
    id: "31",
    name: "Paris",
    events: 49,
    icon: "🗼",
    followed: false,
    color: "bg-orange-500",
    region: "Châu Âu",
  },
  {
    id: "32",
    name: "Stockholm",
    events: 11,
    icon: "🏙️",
    followed: false,
    color: "bg-blue-500",
    region: "Châu Âu",
  },
  {
    id: "33",
    name: "Zurich",
    events: 21,
    icon: "🏰",
    followed: false,
    color: "bg-green-500",
    region: "Châu Âu",
  },
  {
    id: "34",
    name: "Atlanta",
    events: 12,
    icon: "🏙️",
    followed: false,
    color: "bg-yellow-500",
    region: "Bắc Mỹ",
  },
  {
    id: "35",
    name: "Austin",
    events: 21,
    icon: "🏛️",
    followed: false,
    color: "bg-orange-400",
    region: "Bắc Mỹ",
  },
  {
    id: "36",
    name: "Boston",
    events: 27,
    icon: "🌉",
    followed: false,
    color: "bg-orange-600",
    region: "Bắc Mỹ",
  },
  {
    id: "37",
    name: "Calgary",
    events: 6,
    icon: "🗼",
    followed: false,
    color: "bg-blue-500",
    region: "Bắc Mỹ",
  },
  {
    id: "38",
    name: "Chicago",
    events: 21,
    icon: "🏙️",
    followed: false,
    color: "bg-pink-500",
    region: "Bắc Mỹ",
  },
  {
    id: "39",
    name: "Dallas",
    events: 12,
    icon: "🏠",
    followed: false,
    color: "bg-gray-400",
    region: "Bắc Mỹ",
  },
  {
    id: "40",
    name: "Denver",
    events: 16,
    icon: "⛰️",
    followed: false,
    color: "bg-orange-500",
    region: "Bắc Mỹ",
  },
  {
    id: "41",
    name: "Houston",
    events: 15,
    icon: "🏗️",
    followed: false,
    color: "bg-brown-600",
    region: "Bắc Mỹ",
  },
  {
    id: "42",
    name: "Las Vegas",
    events: 16,
    icon: "🎰",
    followed: false,
    color: "bg-yellow-500",
    region: "Bắc Mỹ",
  },
  {
    id: "43",
    name: "Los Angeles",
    events: 42,
    icon: "🎬",
    followed: false,
    color: "bg-green-600",
    region: "Bắc Mỹ",
  },
  {
    id: "44",
    name: "Miami",
    events: 39,
    icon: "🏝️",
    followed: false,
    color: "bg-blue-600",
    region: "Bắc Mỹ",
  },
  {
    id: "45",
    name: "Montreal",
    events: 10,
    icon: "🛳️",
    followed: false,
    color: "bg-blue-400",
    region: "Bắc Mỹ",
  },
  {
    id: "46",
    name: "New York",
    events: 70,
    icon: "🗽",
    followed: false,
    color: "bg-blue-500",
    region: "Bắc Mỹ",
  },
  {
    id: "47",
    name: "Philadelphia",
    events: 12,
    icon: "🏛️",
    followed: false,
    color: "bg-orange-500",
    region: "Bắc Mỹ",
  },
  {
    id: "48",
    name: "Phoenix",
    events: 9,
    icon: "🌵",
    followed: false,
    color: "bg-orange-700",
    region: "Bắc Mỹ",
  },
  {
    id: "49",
    name: "Portland",
    events: 5,
    icon: "🏠",
    followed: false,
    color: "bg-brown-400",
    region: "Bắc Mỹ",
  },
  {
    id: "50",
    name: "San Diego",
    events: 21,
    icon: "🌊",
    followed: false,
    color: "bg-blue-400",
    region: "Bắc Mỹ",
  },
  {
    id: "51",
    name: "San Francisco",
    events: 53,
    icon: "🌉",
    followed: false,
    color: "bg-red-500",
    region: "Bắc Mỹ",
  },
  {
    id: "52",
    name: "Seattle",
    events: 21,
    icon: "🌆",
    followed: false,
    color: "bg-indigo-500",
    region: "Bắc Mỹ",
  },
  {
    id: "53",
    name: "Toronto",
    events: 36,
    icon: "🗼",
    followed: false,
    color: "bg-blue-600",
    region: "Bắc Mỹ",
  },
  {
    id: "54",
    name: "TP. Mexico",
    events: 22,
    icon: "🏰",
    followed: false,
    color: "bg-orange-500",
    region: "Bắc Mỹ",
  },
  {
    id: "55",
    name: "TP. Salt Lake",
    events: 8,
    icon: "⛪",
    followed: false,
    color: "bg-yellow-500",
    region: "Bắc Mỹ",
  },
  {
    id: "56",
    name: "Vancouver",
    events: 17,
    icon: "🗼",
    followed: false,
    color: "bg-yellow-500",
    region: "Bắc Mỹ",
  },
  {
    id: "57",
    name: "Washington, DC",
    events: 25,
    icon: "🏛️",
    followed: false,
    color: "bg-gray-500",
    region: "Bắc Mỹ",
  },
  {
    id: "58",
    name: "Waterloo",
    events: 7,
    icon: "🌿",
    followed: false,
    color: "bg-green-500",
    region: "Bắc Mỹ",
  },
  {
    id: "59",
    name: "Lagos",
    events: 11,
    icon: "🏛️",
    followed: false,
    color: "bg-gray-600",
    region: "Châu Phi",
  },
  {
    id: "60",
    name: "Nairobi",
    events: 10,
    icon: "🏰",
    followed: false,
    color: "bg-green-700",
    region: "Châu Phi",
  },
  {
    id: "61",
    name: "Cairo",
    events: 20,
    icon: "🏺",
    followed: false,
    color: "bg-yellow-600",
    region: "Châu Phi",
  },
  {
    id: "62",
    name: "Cape Town",
    events: 15,
    icon: "⛰️",
    followed: false,
    color: "bg-blue-500",
    region: "Châu Phi",
  },
  {
    id: "63",
    name: "Johannesburg",
    events: 13,
    icon: "🌆",
    followed: false,
    color: "bg-gray-700",
    region: "Châu Phi",
  },
  {
    id: "64",
    name: "Accra",
    events: 9,
    icon: "🏠",
    followed: false,
    color: "bg-orange-600",
    region: "Châu Phi",
  },
  {
    id: "65",
    name: "Casablanca",
    events: 8,
    icon: "🏝️",
    followed: false,
    color: "bg-teal-600",
    region: "Châu Phi",
  },
  {
    id: "66",
    name: "Bogotá",
    events: 5,
    icon: "🏛️",
    followed: false,
    color: "bg-orange-600",
    region: "Nam Mỹ",
  },
  {
    id: "67",
    name: "Buenos Aires",
    events: 15,
    icon: "🗼",
    followed: false,
    color: "bg-red-400",
    region: "Nam Mỹ",
  },
  {
    id: "68",
    name: "Medellín",
    events: 5,
    icon: "🏰",
    followed: false,
    color: "bg-blue-500",
    region: "Nam Mỹ",
  },
  {
    id: "69",
    name: "Rio de Janeiro",
    events: 6,
    icon: "🗿",
    followed: false,
    color: "bg-blue-400",
    region: "Nam Mỹ",
  },
  {
    id: "70",
    name: "São Paulo",
    events: 20,
    icon: "🌉",
    followed: false,
    color: "bg-gray-600",
    region: "Nam Mỹ",
  },
  {
    id: "71",
    name: "Lima",
    events: 12,
    icon: "🏟️",
    followed: false,
    color: "bg-green-600",
    region: "Nam Mỹ",
  },
  {
    id: "72",
    name: "Santiago",
    events: 9,
    icon: "🏔️",
    followed: false,
    color: "bg-purple-600",
    region: "Nam Mỹ",
  },
];
