import type { Event } from "./types"

export const events: Event[] = [
  {
    id: "1",
    title: "Chung kết Web3 Ideathon 2025",
    time: "13:30",
    endTime: "19:00",
    date: "2024-03-28",
    dateLabel: "28 thg 3",
    dayLabel: "Thứ Sáu",
    location: "Hội trường Thành ủy",
    organizer: "Bởi VBI Academy & GFI - Golden Financial Innovation",
    image: "/placeholder.svg?height=200&width=200&text=Web3",
    participants: [
      { id: "1", name: "Nguyễn Văn A", avatar: "/placeholder.svg?height=40&width=40&text=A" },
      { id: "2", name: "Trần Thị B", avatar: "/placeholder.svg?height=40&width=40&text=B" },
      { id: "3", name: "Lê Văn C", avatar: "/placeholder.svg?height=40&width=40&text=C" },
      { id: "4", name: "Phạm Thị D" },
      { id: "5", name: "Hoàng Văn E" },
      { id: "6", name: "Ngô Thị F" },
      { id: "7", name: "Ngô Thị L" },
      // ... thêm 87 người nữa
    ],
    isParticipating: true,
    isUserEvent: false,
  },
  {
    id: "2",
    title: "bac",
    time: "15:30",
    date: "2024-03-29",
    dateLabel: "29 thg 3",
    dayLabel: "Thứ Bảy",
    location: "643 Đ. Phạm Văn Đồng",
    image: "/placeholder.svg?height=200&width=200&text=GUEST",
    participants: [
      { id: "1", name: "Nguyễn Văn A", avatar: "/placeholder.svg?height=40&width=40&text=A" },
      { id: "2", name: "Trần Thị B", avatar: "/placeholder.svg?height=40&width=40&text=B" },
      { id: "3", name: "Trần Thị B", avatar: "/placeholder.svg?height=40&width=40&text=B" },
      { id: "4", name: "Trần Thị B", avatar: "/placeholder.svg?height=40&width=40&text=B" },
      { id: "5", name: "Trần Thị B", avatar: "/placeholder.svg?height=40&width=40&text=B" },
      { id: "6", name: "Trần Thị B", avatar: "/placeholder.svg?height=40&width=40&text=B" },
      { id: "7", name: "Trần Thị B", avatar: "/placeholder.svg?height=40&width=40&text=B" },
      { id: "8", name: "Trần Thị B", avatar: "/placeholder.svg?height=40&width=40&text=B" },
      { id: "9", name: "Trần Thị B", avatar: "/placeholder.svg?height=40&width=40&text=B" },
      
    ],
    isUserEvent: true,
    isParticipating: false,
  },
  {
    id: "3",
    title: "timer",
    time: "0:30",
    date: "2024-06-13",
    dateLabel: "13 thg 6",
    dayLabel: "Thứ Sáu",
    location: "",
    image: "/placeholder.svg?height=200&width=200&text=",
    participants: [],
    missingLocation: true,
    isUserEvent: true,
    isParticipating: false,
  },
  {
    id: "4",
    title: "timer",
    time: "0:30",
    date: "2024-06-13",
    dateLabel: "13 thg 6",
    dayLabel: "Thứ Sáu",
    location: "",
    image: "/placeholder.svg?height=200&width=200&text=",
    participants: [],
    missingLocation: true,
    isUserEvent: true,
    isParticipating: false,
  },
  {
    id: "5",
    title: "bac",
    time: "15:30",
    date: "2024-10-29",
    dateLabel: "29 thg 3",
    dayLabel: "Thứ Bảy",
    location: "643 Đ. Phạm Văn Đồng",
    image: "/placeholder.svg?height=200&width=200&text=GUEST",
    participants: [
      { id: "1", name: "Nguyễn Văn A", avatar: "/placeholder.svg?height=40&width=40&text=A" },
      { id: "2", name: "Trần Thị B", avatar: "/placeholder.svg?height=40&width=40&text=B" },
      { id: "3", name: "Trần Thị B", avatar: "/placeholder.svg?height=40&width=40&text=B" },
      { id: "4", name: "Trần Thị B", avatar: "/placeholder.svg?height=40&width=40&text=B" },
    ],
    isUserEvent: true,
    isParticipating: false,
  },
]

