import type { Event } from "./types";

export const events: Event[] = [
  {
    id: "1",
    title: "Chung kết Web3 Ideathon 2025",
    time: "13:30",
    endTime: "19:00",
    date: "2024-03-28",
    dateLabel: "28 thg 3",
    dayLabel: "Thứ Sáu",
    location: "Hội trường Thành ủy",
    organizer: "Bởi VBI Academy & GFI - Golden Financial Innovation",
    image: "/images/events/web3-ideathon.jpg",
    participants: [
      { id: "1", name: "Nguyễn Văn A", avatar: "/images/avatars/user1.jpg" },
      { id: "2", name: "Trần Thị B", avatar: "/images/avatars/user2.jpg" },
      { id: "3", name: "Lê Văn C", avatar: "/images/avatars/user3.jpg" },
      { id: "4", name: "Phạm Thị D", avatar: "/images/avatars/user4.jpg" },
      { id: "5", name: "Hoàng Văn E", avatar: "/images/avatars/user5.jpg" },
      { id: "6", name: "Ngô Thị F", avatar: "/images/avatars/user6.jpg" },
      { id: "7", name: "Ngô Thị L", avatar: "/images/avatars/user7.jpg" },
      // ... thêm 87 người nữa
    ],
    isParticipating: true,
    isUserEvent: false,
  },
  {
    id: "2",
    title: "Blockchain Workshop",
    time: "15:30",
    date: "2024-03-29",
    dateLabel: "29 thg 3",
    dayLabel: "Thứ Bảy",
    location: "643 Đ. Phạm Văn Đồng",
    image: "/images/events/blockchain-workshop.jpg",
    participants: [
      { id: "1", name: "Nguyễn Văn A", avatar: "/images/avatars/user8.jpg" },
      { id: "2", name: "Trần Thị B", avatar: "/images/avatars/user9.jpg" },
      { id: "3", name: "Lê Văn C", avatar: "/images/avatars/user10.jpg" },
    ],
    isUserEvent: true,
    isParticipating: false,
  },
  {
    id: "3",
    title: "timer",
    time: "0:30",
    date: "2024-06-13",
    dateLabel: "13 thg 6",
    dayLabel: "Thứ Sáu",
    location: "",
    image: "/placeholder.svg?height=200&width=200&text=",
    participants: [],
    missingLocation: true,
    isUserEvent: true,
    isParticipating: false,
  },
  {
    id: "4",
    title: "timer",
    time: "0:30",
    date: "2024-06-13",
    dateLabel: "13 thg 6",
    dayLabel: "Thứ Sáu",
    location: "",
    image: "/placeholder.svg?height=200&width=200&text=",
    participants: [],
    missingLocation: true,
    isUserEvent: true,
    isParticipating: false,
  },
  {
    id: "5",
    title: "bac",
    time: "15:30",
    date: "2024-10-29",
    dateLabel: "29 thg 3",
    dayLabel: "Thứ Bảy",
    location: "643 Đ. Phạm Văn Đồng",
    image: "/placeholder.svg?height=200&width=200&text=GUEST",
    participants: [
      {
        id: "1",
        name: "Nguyễn Văn A",
        avatar: "/placeholder.svg?height=40&width=40&text=A",
      },
      {
        id: "2",
        name: "Trần Thị B",
        avatar: "/placeholder.svg?height=40&width=40&text=B",
      },
      {
        id: "3",
        name: "Trần Thị B",
        avatar: "/placeholder.svg?height=40&width=40&text=B",
      },
      {
        id: "4",
        name: "Trần Thị B",
        avatar: "/placeholder.svg?height=40&width=40&text=B",
      },
    ],
    isUserEvent: true,
    isParticipating: false,
  },
];
